### ISSUE TITLE
Problem with first run: Couldn't start xxx

### ISSUE THREAD

**Issue by hrosenbe** [vmware/weathervane#47]
A user has reported an inability to get the first run to work.  The output includes the following:

Tue Jun 27 10:08:43 2017: Couldn't start appServer tomcat on AuctionDriver1. Check logs for run.
Tue Jun 27 10:08:43 2017: Couldn't start webServer nginx on AuctionDriver1. Check logs for run.

They need guidance on how to troubleshoot this issue.

**Comment by hrosenbe** [comment]
The logs that should be helpful will be in the output directory under /root/weathervane/output/3/setupLogs/.

There should be files whose names look like StartNginx... and StartTomcat...

Can you please attach those to this issue, along with the files from that directory whose names start with isUp

**Comment by hrosenbe** [comment]
Also, this makes it clear that we need a good troubleshooting guide.  I have create issue #49 for this.

**Comment by izaakk** [comment]
Attaching log files.. We tried to start services manually, but still we got the same error message from weathervane.pl



[isUp-Auction.log.txt](https://github.com/vmware/weathervane/files/1109613/isUp-Auction.log.txt)
[isUpDataServices-Auction.log.txt](https://github.com/vmware/weathervane/files/1109614/isUpDataServices-Auction.log.txt)
[StartNginx-AuctionDriver1.log.txt](https://github.com/vmware/weathervane/files/1109615/StartNginx-AuctionDriver1.log.txt)
[StartTomcat-AuctionDriver1.log.txt](https://github.com/vmware/weathervane/files/1109616/StartTomcat-AuctionDriver1.log.txt)

**Comment by hrosenbe** [comment]
I do see one error in isUp-Auction.log.txt that might be informative.  It is:

Your requested host "auctiondriver1" could not be resolved by DNS.

Did you start the DNS server on your Centos host?  
- Use `systemctl status named` to check whether DNS is running.
- if not, use `systemctl start named` to start it running.

**Comment by izaakk** [comment]
Yes, we started the service, Otherwise it would fail right away, within seconds.

**Comment by hrosenbe** [comment]
Can you please try this for me:

* Perform the run with the addition of the --nostopOnFailure command-line parameter.  This will look like:
  * `./weathervane.pl --nostopOnFailure`
  * Adding `--nostopOnFailure` causes the run harness to leave the various services running when it exits after a failure.
* Once the run harness has exited.  Execute the following from the command-line:
  * `curl -s http://AuctionDriver1:8080/auction/healthCheck`. This should return "alive".
  * `curl -s http://auctiondriver1:8080/auction/healthCheck`. Note the lower case. This should also return "alive".
  * `curl -s -w "%{http_code}\n" -o /dev/null http://AuctionDriver1:9080`. This should return 200.

If any of those command returns anything other than the expected response, can you please post it here.

**Comment by izaakk** [comment]
The first two curls return:

`<HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (dns_unresolved_hostname)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your requested host "auctiondriver1" could not be resolved by DNS.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">

</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>`

and the last one returns a 404 Error.

Just to verify again our DNS we ran:

`[root@localhost ~]# systemctl status named
● named.service - Berkeley Internet Name Domain (DNS)
   Loaded: loaded (/usr/lib/systemd/system/named.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-06-28 11:17:06 MST; 10min ago
  Process: 16880 ExecStop=/bin/sh -c /usr/sbin/rndc stop > /dev/null 2>&1 || /bin/kill -TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 16896 ExecStart=/usr/sbin/named -u named $OPTIONS (code=exited, status=0/SUCCESS)
  Process: 16891 ExecStartPre=/bin/bash -c if [ ! "$DISABLE_ZONE_CHECKING" == "yes" ]; then /usr/sbin/named-checkconf -z /etc/named.conf; else echo "Checking of zone files is disabled"; fi (code=exited, status=0/SUCCESS)
 Main PID: 16897 (named)
   Memory: 33.6M
   CGroup: /system.slice/named.service
           └─16897 /usr/sbin/named -u named -4

Jun 28 11:17:06 localhost.localdomain named[16897]: managed-keys-zone: journal file is out of date: removing journal file
Jun 28 11:17:06 localhost.localdomain named[16897]: managed-keys-zone: loaded serial 6
Jun 28 11:17:06 localhost.localdomain named[16897]: zone 0.in-addr.arpa/IN: loaded serial 0
Jun 28 11:17:06 localhost.localdomain named[16897]: zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
Jun 28 11:17:06 localhost.localdomain named[16897]: zone localhost/IN: loaded serial 0
Jun 28 11:17:06 localhost.localdomain named[16897]: zone localhost.localdomain/IN: loaded serial 0
Jun 28 11:17:06 localhost.localdomain named[16897]: zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
Jun 28 11:17:06 localhost.localdomain named[16897]: zone weathervane/IN: loaded serial 2015051800
Jun 28 11:17:06 localhost.localdomain named[16897]: all zones loaded
Jun 28 11:17:06 localhost.localdomain named[16897]: running`

**Comment by hrosenbe** [comment]
Can you please post the output from the following commands:

* `ls -lh /opt/apache-tomcat-auction1/webapps/`
* `ls -lh /usr/share/nginx/html/`

**Comment by izaakk** [comment]
`[root@localhost ~]# ls -lh /opt/apache-tomcat-auction1/webapps/
total 45M
drwxr-x---  4 root root   37 Jun 27 16:42 auction
-rw-r--r--. 1 root root  44M Jun 27 15:46 auction.war
drwxr-x---  9 root root  120 Jun 27 16:42 auctionWeb
-rw-r--r--. 1 root root 519K Jun 27 15:46 auctionWeb.war
drwxr-x---  9 root root  120 Jun 27 16:42 ROOT`

`[root@localhost ~]# ls -lh /usr/share/nginx/html/
total 20K
drwxrwxr-x 3 nginx nginx  169 May 12 12:38 css
drwxrwxr-x 2 nginx nginx  167 May 12 12:38 fonts
drwxrwxr-x 2 nginx nginx 4.0K May 12 12:38 images
-rw-rw-r-- 1 nginx nginx 5.4K May 12 12:38 index.html
drwxrwxr-x 3 nginx nginx 4.0K May 12 12:38 js
drwxrwxr-x 2 nginx nginx 4.0K May 12 12:38 templates
drwxrwxr-x 2 nginx nginx   21 May 12 12:38 WEB-INF`

We are behind a corporate proxy, I think that probably makes a difference

**Comment by hrosenbe** [comment]
I was wondering whether the app and web servers didn't have the right files, but everything seems correct.  Can you upload the following files:

* /var/named/weathervane.forward.zone
* /etc/hosts

**Comment by izaakk** [comment]
Here
[hosts.txt](https://github.com/vmware/weathervane/files/1109880/hosts.txt)
[weathervane.forward.zone.txt](https://github.com/vmware/weathervane/files/1109881/weathervane.forward.zone.txt)

**Comment by hrosenbe** [comment]
Those look fine.  Can you also upload /etc/resolv.conf

What happens when you run the following from the command-line: `nslookup auctiondriver1`?

**Comment by izaakk** [comment]
> [root@localhost ~]# cat /etc/resolv.conf
search	weathervane eng.vmware.com
nameserver 127.0.0.1
#nameserver 192.168.239.149
[root@localhost ~]# nslookup auctiondriver1
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:	auctiondriver1.weathervane
Address: 127.0.0.1

**Comment by izaakk** [comment]
ok, so after some experiments we realized that being behind a corporate proxy is a pain.. we needed to configure our environment to not use the proxy when resolving names for auction app. 
I think anyways is worth documenting this troubleshoot with DNS problems behind a proxy.
Its working now!

**Comment by hrosenbe** [comment]
Thank you for the update.  I was having trouble coming up with a good explanation for what was happening.  

I have opened issue #49 to track documenting this problem.  If it doesn't reveal any internal knowledge, would you mind explaining exactly how you changed your configuration to make this work?

**Comment by izaakk** [comment]
Thank you for pointing us in the right direction.

Since we are behind corporate proxy, we need to set http_proxy and https_proxy env variables.

We simply did:

`export no_proxy=localhost,ips_to_ignore`

DNS was looking for `auctiondriver1` from the proxy server, which we use to conect to the outside world.

**Comment by hrosenbe** [comment]
Thanks for explaining that.  

I am going to close this issue, but feel free to open another if you have any other issues.
