### ISSUE TITLE
Weathervane collected hardware resource utilization differs significantly from those exposed in vsphere web client

### ISSUE THREAD

**Issue by PatrickGuo** [vmware/weathervane#51]
I'm running each service component of Weathervane benchmark in a VM instance, and all the VMs are operated by a vCenter. 

A confusing thing is that the average CPU utilization shown in weathervaneResult.csv is always significantly higher than the corresponding data collected from the vcenter web client. I specifically collect the data when the workload is in the steady state, so theoretically the two data should be very close (as weathervane is using 'sar' command to collect statistics, while vcenter I suppose is using esxtop to collect vm specific data from each world).

I would really appreciate if someone could provide any insight, thanks.

**Comment by hrosenbe** [comment]
I believe that the most common reasons that the in-guest stats would differ from those collected using esxtop or vCenter would be due to power management or hyperthreading.  

The difference may also have to do with which vCenter metric you are observing, e.g. %USED versus %UTIL.  These metrics are affected by both hyperthreading and power management.  There is a good discussion here, https://communities.vmware.com/docs/DOC-9279, about how those those things affect the CPU metrics.  The document is old, but it is my understanding that it is still basically accurate.

One way to tell whether the difference has to do with power management would be to set your ESXi server(s) to the High Performance power management policy and see if that eliminates the discrepancy.
